---

- name: Setup ufw firewall
  hosts: all
  tasks:

  - name: Apply ufw rule for ssh/2223
    become: yes
    ufw:
      rule: limit
      port: 2223
      proto: tcp
      log: no

  - name: Disable ufw rule for ssh/22
    become: yes
    ufw:
      rule: deny
      port: 22
      proto: tcp
      log: no

  - name: Apply ufw rules
    become: yes
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
      log: no
    with_items:
    - "http"
    - "https"
  
  - name: Enable ufw
    become: yes
    ufw:
      direction: incoming
      default: deny
      logging: off
      state: enabled